devtools_packages:
  - btop
  - git
  - stow
  - fzf
  - direnv
  - lsd
  - python3-pip
  - python3-pipx
  - unzip
  - curl
  - wget
  - tmux
  - kubectl
  - ansible
  - base-devel
  - luarocks
  - lua-devel
  - lua-language-server
  - ripgrep
  - fd
  - ImageMagick
  - ghostscript
  - lazygit
  - cmake
